name: CI
on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always
  MOONFIRE_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  rust:
    name: Rust ${{ matrix.rust }}
    strategy:
      matrix:
        rust: [ "stable", "1.70", "nightly" ]
        include:
          - rust: nightly
            extra_args: "--features nightly --benches"
          - rust: stable
            extra_components: rustfmt
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            server/target
          key: cargo-${{ matrix.rust }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-${{ matrix.rust }}-
            cargo-
      - name: Install dependencies
        # The retry here is to work around "Unable to connect to azure.archive.ubuntu.com" errors.
        # https://github.com/actions/runner-images/issues/6894
        run: sudo apt-get --option=APT::Acquire::Retries=3 update && sudo apt-get --option=APT::Acquire::Retries=3 install libncurses-dev libsqlite3-dev pkgconf
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: ${{ matrix.extra_components }}
      - name: Test
        run: cd server && cargo test ${{ matrix.extra_args }} --all
        continue-on-error: ${{ matrix.rust == 'nightly' }}
      - name: Check formatting
        if: matrix.rust == 'stable'
        run: cd server && cargo fmt --all -- --check
  js:
    name: Node ${{ matrix.node }}
    strategy:
      matrix:
        node: [ "14", "16", "18" ]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: cd ui && npm ci
      - run: cd ui && npm run build
      - run: cd ui && npm run test
      - run: cd ui && npm run lint
      - run: cd ui && npm run check-format
  license:
    name: Check copyright/license headers
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: find . -type f -print0 | xargs -0 .github/workflows/check-license.py
